name: CI-Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Ejecuta en Linux y Windows
        python-version: ["3.8", "3.9", "3.10"]  # Pruebas en varias versiones de Python

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
        shell: bash  # Asegura compatibilidad en Windows y Linux

      - name: Ejecutar pruebas
        run: python -m unittest tests
        shell: bash  # Importante para Windows
